sudo: required
services:
    - docker

before_install:
    - docker build -t youssef/docker-react -f Dockerfile.dev .

script:
    #- docker run youssef/docker-react npm run test -- --coverage
    - docker run -e CI=true youssef/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "Dockerreact-env-1"
    bucket_name: "elasticbeanstalk-us-east-2-701169926941"
    bucket_path: "docker-react"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_acces_key:
        secure: $AWS_SECRET_KEY