sudo: required
services:
    - docker


before_install:
    - docker build -t youssef/docker-react -f Dockerfile.dev .

script:
    #- docker run youssef/docker-react npm run test -- --coverage
    - docker run -e CI=true youssef/docker-react npm run test

